//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.19 at 12:55:58 ���� CST 
//

package com.bulain.swift.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AccountReport1 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AccountReport1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Acct" type="{urn:iso:std:iso:20022:tech:xsd:acmt.014.001.01}CustomerAccount1"/>
 *         &lt;element name="UndrlygMstrAgrmt" type="{urn:iso:std:iso:20022:tech:xsd:acmt.014.001.01}ContractDocument1" minOccurs="0"/>
 *         &lt;element name="CtrctDts" type="{urn:iso:std:iso:20022:tech:xsd:acmt.014.001.01}AccountContract3" minOccurs="0"/>
 *         &lt;element name="Mndt" type="{urn:iso:std:iso:20022:tech:xsd:acmt.014.001.01}OperationMandate1" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RefAcct" type="{urn:iso:std:iso:20022:tech:xsd:acmt.014.001.01}CashAccount16" minOccurs="0"/>
 *         &lt;element name="BalTrfAcct" type="{urn:iso:std:iso:20022:tech:xsd:acmt.014.001.01}AccountForAction1" minOccurs="0"/>
 *         &lt;element name="TrfAcctSvcrId" type="{urn:iso:std:iso:20022:tech:xsd:acmt.014.001.01}BranchAndFinancialInstitutionIdentification4" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountReport1", propOrder = {"acct", "undrlygMstrAgrmt", "ctrctDts", "mndt", "refAcct", "balTrfAcct",
        "trfAcctSvcrId"})
public class AccountReport1 {

    @XmlElement(name = "Acct", required = true)
    protected CustomerAccount1 acct;
    @XmlElement(name = "UndrlygMstrAgrmt")
    protected ContractDocument1 undrlygMstrAgrmt;
    @XmlElement(name = "CtrctDts")
    protected AccountContract3 ctrctDts;
    @XmlElement(name = "Mndt")
    protected List<OperationMandate1> mndt;
    @XmlElement(name = "RefAcct")
    protected CashAccount16 refAcct;
    @XmlElement(name = "BalTrfAcct")
    protected AccountForAction1 balTrfAcct;
    @XmlElement(name = "TrfAcctSvcrId")
    protected BranchAndFinancialInstitutionIdentification4 trfAcctSvcrId;

    /**
     * Gets the value of the acct property.
     * 
     * @return possible object is {@link CustomerAccount1 }
     * 
     */
    public CustomerAccount1 getAcct() {
        return acct;
    }

    /**
     * Sets the value of the acct property.
     * 
     * @param value
     *            allowed object is {@link CustomerAccount1 }
     * 
     */
    public void setAcct(CustomerAccount1 value) {
        this.acct = value;
    }

    /**
     * Gets the value of the undrlygMstrAgrmt property.
     * 
     * @return possible object is {@link ContractDocument1 }
     * 
     */
    public ContractDocument1 getUndrlygMstrAgrmt() {
        return undrlygMstrAgrmt;
    }

    /**
     * Sets the value of the undrlygMstrAgrmt property.
     * 
     * @param value
     *            allowed object is {@link ContractDocument1 }
     * 
     */
    public void setUndrlygMstrAgrmt(ContractDocument1 value) {
        this.undrlygMstrAgrmt = value;
    }

    /**
     * Gets the value of the ctrctDts property.
     * 
     * @return possible object is {@link AccountContract3 }
     * 
     */
    public AccountContract3 getCtrctDts() {
        return ctrctDts;
    }

    /**
     * Sets the value of the ctrctDts property.
     * 
     * @param value
     *            allowed object is {@link AccountContract3 }
     * 
     */
    public void setCtrctDts(AccountContract3 value) {
        this.ctrctDts = value;
    }

    /**
     * Gets the value of the mndt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the mndt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getMndt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationMandate1 }
     * 
     * 
     */
    public List<OperationMandate1> getMndt() {
        if (mndt == null) {
            mndt = new ArrayList<OperationMandate1>();
        }
        return this.mndt;
    }

    /**
     * Gets the value of the refAcct property.
     * 
     * @return possible object is {@link CashAccount16 }
     * 
     */
    public CashAccount16 getRefAcct() {
        return refAcct;
    }

    /**
     * Sets the value of the refAcct property.
     * 
     * @param value
     *            allowed object is {@link CashAccount16 }
     * 
     */
    public void setRefAcct(CashAccount16 value) {
        this.refAcct = value;
    }

    /**
     * Gets the value of the balTrfAcct property.
     * 
     * @return possible object is {@link AccountForAction1 }
     * 
     */
    public AccountForAction1 getBalTrfAcct() {
        return balTrfAcct;
    }

    /**
     * Sets the value of the balTrfAcct property.
     * 
     * @param value
     *            allowed object is {@link AccountForAction1 }
     * 
     */
    public void setBalTrfAcct(AccountForAction1 value) {
        this.balTrfAcct = value;
    }

    /**
     * Gets the value of the trfAcctSvcrId property.
     * 
     * @return possible object is
     *         {@link BranchAndFinancialInstitutionIdentification4 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification4 getTrfAcctSvcrId() {
        return trfAcctSvcrId;
    }

    /**
     * Sets the value of the trfAcctSvcrId property.
     * 
     * @param value
     *            allowed object is
     *            {@link BranchAndFinancialInstitutionIdentification4 }
     * 
     */
    public void setTrfAcctSvcrId(BranchAndFinancialInstitutionIdentification4 value) {
        this.trfAcctSvcrId = value;
    }

}
