//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.19 at 12:56:09 ���� CST 
//

package com.bulain.swift.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Authorisation1 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Authorisation1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MinAmtPerTx" type="{urn:iso:std:iso:20022:tech:xsd:acmt.017.001.01}ActiveCurrencyAndAmount"/>
 *         &lt;element name="MaxAmtPerTx" type="{urn:iso:std:iso:20022:tech:xsd:acmt.017.001.01}ActiveCurrencyAndAmount"/>
 *         &lt;element name="MaxAmtByPrd" type="{urn:iso:std:iso:20022:tech:xsd:acmt.017.001.01}MaximumAmountByPeriod1" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Authorisation1", propOrder = {"minAmtPerTx", "maxAmtPerTx", "maxAmtByPrd"})
public class Authorisation1 {

    @XmlElement(name = "MinAmtPerTx", required = true)
    protected ActiveCurrencyAndAmount minAmtPerTx;
    @XmlElement(name = "MaxAmtPerTx", required = true)
    protected ActiveCurrencyAndAmount maxAmtPerTx;
    @XmlElement(name = "MaxAmtByPrd")
    protected List<MaximumAmountByPeriod1> maxAmtByPrd;

    /**
     * Gets the value of the minAmtPerTx property.
     * 
     * @return possible object is {@link ActiveCurrencyAndAmount }
     * 
     */
    public ActiveCurrencyAndAmount getMinAmtPerTx() {
        return minAmtPerTx;
    }

    /**
     * Sets the value of the minAmtPerTx property.
     * 
     * @param value
     *            allowed object is {@link ActiveCurrencyAndAmount }
     * 
     */
    public void setMinAmtPerTx(ActiveCurrencyAndAmount value) {
        this.minAmtPerTx = value;
    }

    /**
     * Gets the value of the maxAmtPerTx property.
     * 
     * @return possible object is {@link ActiveCurrencyAndAmount }
     * 
     */
    public ActiveCurrencyAndAmount getMaxAmtPerTx() {
        return maxAmtPerTx;
    }

    /**
     * Sets the value of the maxAmtPerTx property.
     * 
     * @param value
     *            allowed object is {@link ActiveCurrencyAndAmount }
     * 
     */
    public void setMaxAmtPerTx(ActiveCurrencyAndAmount value) {
        this.maxAmtPerTx = value;
    }

    /**
     * Gets the value of the maxAmtByPrd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the maxAmtByPrd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getMaxAmtByPrd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MaximumAmountByPeriod1 }
     * 
     * 
     */
    public List<MaximumAmountByPeriod1> getMaxAmtByPrd() {
        if (maxAmtByPrd == null) {
            maxAmtByPrd = new ArrayList<MaximumAmountByPeriod1>();
        }
        return this.maxAmtByPrd;
    }

}
