//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.19 at 01:03:20 ���� CST 
//

package com.bulain.swift.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Document complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcctReqAck" type="{urn:iso:std:iso:20022:tech:xsd:acmt.010.001.01}AccountRequestAcknowledgementV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {"acctReqAck"})
public class DocumentReqAck {

    @XmlElement(name = "AcctReqAck", required = true)
    protected AccountRequestAcknowledgementV01 acctReqAck;

    /**
     * Gets the value of the acctReqAck property.
     * 
     * @return possible object is {@link AccountRequestAcknowledgementV01 }
     * 
     */
    public AccountRequestAcknowledgementV01 getAcctReqAck() {
        return acctReqAck;
    }

    /**
     * Sets the value of the acctReqAck property.
     * 
     * @param value
     *            allowed object is {@link AccountRequestAcknowledgementV01 }
     * 
     */
    public void setAcctReqAck(AccountRequestAcknowledgementV01 value) {
        this.acctReqAck = value;
    }

}
